services:
  - type: web
    name: student-resources-backend
    env: docker
    root: backend
    dockerfilePath: Dockerfile
    repo: https://github.com/your-user/your-repo  # <-- REPLACE with your repo URL
    branch: main
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<MYSQL_HOST>:3306/student_resources?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: mohan
      - key: SPRING_DATASOURCE_PASSWORD
        value: ChangeThisStrongPassword!
      - key: SPRING_DATASOURCE_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: SPRING_JPA_HBM2DDL
        value: update
      - key: FILE_UPLOAD_DIR
        value: /data/uploads
      - key: JAVA_OPTS
        value: -Xmx512m

# Note: this file no longer creates a managed database. For MySQL, provide an external MySQL host
# and set SPRING_DATASOURCE_URL / USER / PASSWORD in the Render service UI (do not commit real secrets).
