# Render service template — Dockerfile path is relative to repo root
services:
  - type: web
    name: student-resources-backend
    env: docker
    root: .
    dockerfilePath: backend/Dockerfile
    repo: https://github.com/your-user/your-repo  # <-- REPLACE with your repo URL
    branch: main
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<MYSQL_HOST>:3306/student_resources?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: mohan
      - key: SPRING_DATASOURCE_PASSWORD
        value: ChangeThisStrongPassword!
      - key: SPRING_DATASOURCE_DRIVER
        value: com.mysql.cj.jdbc.Driver
      - key: SPRING_JPA_HBM2DDL
        value: update
      - key: FILE_UPLOAD_DIR
        value: /data/uploads
      - key: JAVA_OPTS
        value: -Xmx512m

# NOTE: Do NOT commit real secrets. Replace placeholders above and/or set these env vars in the Render UI.
