# Render service template — Dockerfile path is relative to repo root
services:
  - type: web
    name: student-resources-backend
    env: docker
    root: backend
    dockerfilePath: Dockerfile
    repo: https://github.com/Mohan7989/MRCA_FINAL_PROJECT_OUTPUT  # replace if different
    branch: main
    plan: free
    envVars:
      # Do NOT set SPRING_DATASOURCE_URL here with a placeholder.
      # Set actual DB credentials in the Render service UI (Environment -> Add Environment Variable).
      - key: SPRING_JPA_HBM2DDL
        value: update
      - key: FILE_UPLOAD_DIR
        value: /data/uploads
      - key: JAVA_OPTS
        value: -Xmx512m

# NOTE: Do NOT commit real secrets. Set SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD
# in the Render dashboard for the service (Environment -> Environment Variables) with the real MySQL host and credentials.
